"""empty message

Revision ID: 05a1f98ac35e
Revises: 40567d4d2fe7
Create Date: 2024-12-04 18:51:40.631482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05a1f98ac35e'
down_revision: Union[str, None] = '40567d4d2fe7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('accessLevel', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'accessLevel')
    # ### end Alembic commands ###
